spring.application.name=DevFlow-api
# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/devflow
spring.datasource.username=devflow_user
spring.datasource.password=devflow_pass
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# App
server.port=8080

# Actuator
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always

devflow.terraform.module-path=/absolute/path/to/your/devflow/infrastructure/terraform/modules/k8s-namespace
devflow.terraform.working-dir=/tmp/devflow-terraform